//! Maintained telemetry adapter field order, encoding and units.

record_layout! { service_telemetry, "SERVICE_TELEMETRY";
	(CALLBACK_DEPTH, 2, "exact u16 words, 0..65535 each", "count", "callback depth"),
	(CALLBACK_CAPACITY, 2, "exact u16 words, 0..65535 each", "count", "callback capacity"),
	(CALLBACK_HIGH_WATER, 2, "exact u16 words, 0..65535 each", "count", "callback high water"),
	(CONTINUATION_DEPTH, 2, "exact u16 words, 0..65535 each", "count", "continuation depth"),
	(CONTINUATION_CAPACITY, 2, "exact u16 words, 0..65535 each", "count", "continuation capacity"),
	(CONTINUATION_HIGH_WATER, 2, "exact u16 words, 0..65535 each", "count", "continuation high water"),
	(OLDEST_CALLBACK_AGE, 4, "exact u16 words, 0..65535 each", "ticks", "oldest callback age"),
	(CALLBACK_ENQUEUED, 4, "exact u16 words, 0..65535 each", "count", "callback enqueued"),
	(CALLBACK_DRAINED, 4, "exact u16 words, 0..65535 each", "count", "callback drained"),
	(CALLBACK_REJECTED, 4, "exact u16 words, 0..65535 each", "count", "callback rejected"),
	(CONTINUATION_TIMEOUTS, 4, "exact u16 words, 0..65535 each", "count", "continuation timeouts"),
	(REQUEST_TIMEOUTS, 4, "exact u16 words, 0..65535 each", "count", "request timeouts"),
	(PROTOCOL_ERRORS, 4, "exact u16 words, 0..65535 each", "count", "protocol errors"),
	(ENQUEUED_BY_KIND, 4 * dogmos_protocol::CALLBACK_EVENT_KIND_COUNT, "exact u16 words, 0..65535 each", "per-kind counters", "enqueued by kind"),
	(DRAINED_BY_KIND, 4 * dogmos_protocol::CALLBACK_EVENT_KIND_COUNT, "exact u16 words, 0..65535 each", "per-kind counters", "drained by kind"),
	(REJECTED_BY_KIND, 4 * dogmos_protocol::CALLBACK_EVENT_KIND_COUNT, "exact u16 words, 0..65535 each", "per-kind counters", "rejected by kind"),
	(PROCESS_FLAGS, 2, "exact u16 words, 0..65535 each", "availability flags", "process flags"),
	(RSS, 4, "exact u16 words, 0..65535 each", "bytes", "rss"),
	(CPU, 4, "exact u16 words, 0..65535 each", "milliseconds", "cpu"),
	(GENERAL_CALLBACK_DEPTH, 2, "exact u16 words, 0..65535 each", "count", "general callback depth"),
	(REACTION_CALLBACK_DEPTH, 2, "exact u16 words, 0..65535 each", "count", "reaction callback depth"),
	(REACTION_TRANSACTION_DEPTH, 2, "exact u16 words, 0..65535 each", "count", "reaction transaction depth"),
	(REACTION_TRANSACTION_HIGH_WATER, 2, "exact u16 words, 0..65535 each", "count", "reaction transaction high water"),
	(FRONTIER_COUNT, 2, "exact u16 words, 0..65535 each", "count", "frontier count"),
	(STAGE_KIND, 2, "exact u16 words, 0..65535 each", "count", "stage kind"),
	(FRONTIER_UPLOAD_BYTES, 4, "exact u16 words, 0..65535 each", "bytes", "frontier upload bytes"),
	(STAGE_EPOCH, 4, "exact u16 words, 0..65535 each", "identity", "stage epoch"),
	(STAGE_CURSOR, 2, "exact u16 words, 0..65535 each", "count", "stage cursor"),
	(STAGE_REMAINING, 2, "exact u16 words, 0..65535 each", "count", "stage remaining"),
	(TOPOLOGY_REVISION, 4, "exact u16 words, 0..65535 each", "identity", "topology revision"),
	(REUSABLE_WORKSET_BYTES, 4, "exact u16 words, 0..65535 each", "bytes", "reusable workset bytes"),
	(PACKED_TOPOLOGY_BYTES, 4, "exact u16 words, 0..65535 each", "bytes", "packed topology bytes"),
	(JOB, 4, "exact u16 words, 0..65535 each", "identity", "job"),
	(JOB_STATUS, 2, "exact u16 words, 0..65535 each", "status", "job status"),
	(JOB_AGE, 4, "exact u16 words, 0..65535 each", "nanoseconds", "job age"),
	(PREPARE_CALLS, 4, "exact u16 words, 0..65535 each", "count", "prepare calls"),
	(PREPARE_TOTAL_NS, 4, "exact u16 words, 0..65535 each", "nanoseconds", "prepare total ns"),
	(PREPARE_MAX_NS, 4, "exact u16 words, 0..65535 each", "nanoseconds", "prepare max ns"),
	(PREPARE_LAST_NS, 4, "exact u16 words, 0..65535 each", "nanoseconds", "prepare last ns"),
	(COMMIT_CALLS, 4, "exact u16 words, 0..65535 each", "count", "commit calls"),
	(COMMIT_TOTAL_NS, 4, "exact u16 words, 0..65535 each", "nanoseconds", "commit total ns"),
	(COMMIT_MAX_NS, 4, "exact u16 words, 0..65535 each", "nanoseconds", "commit max ns"),
	(COMMIT_LAST_NS, 4, "exact u16 words, 0..65535 each", "nanoseconds", "commit last ns"),
	(PUBLICATION_RETRIES, 4, "exact u16 words, 0..65535 each", "count", "publication retries"),
	(COMPLETED_JOBS, 4, "exact u16 words, 0..65535 each", "count", "completed jobs"),
	(CANCELLED_JOBS, 4, "exact u16 words, 0..65535 each", "count", "cancelled jobs"),
}

pub(crate) const LAYOUTS: &[&crate::adapter_layout::Layout] = &[&service_telemetry::LAYOUT];
