/** Checks the public pipeline adapter and existing native bulk operation against literal conserved states. */
/proc/verify_pipenet_reconciliation()
	for(var/native in list(FALSE, TRUE))
		var/datum/gas_mixture/first = new(100)
		var/datum/gas_mixture/second = new(300)
		first.set_moles(GAS_O2, 10)
		first.set_moles(GAS_N2, 0.006)
		first.set_temperature(600)
		second.set_moles(GAS_O2, 30)
		second.set_moles(GAS_N2, 0.002)
		second.set_temperature(300)
		var/energy = first.thermal_energy() + second.thermal_energy()
		var/list/mixes = list(first, second, first)
		if(native)
			equalize_all_gases_in_list(mixes)
		else
			dogmos_reconcile_pipeline_mixtures(mixes)
		if(abs(first.get_moles(GAS_O2) - 10) > 0.00001 || abs(second.get_moles(GAS_O2) - 30) > 0.00001)
			CRASH("Pipeline reconciliation changed mass or counted duplicates.")
		if(abs(first.get_moles(GAS_N2) - 0.002) > 0.000001 || abs(second.get_moles(GAS_N2) - 0.006) > 0.000001)
			CRASH("Pipeline reconciliation deleted sub-centimole gas.")
		if(first.return_volume() != 100 || second.return_volume() != 300 || abs(first.return_temperature() - second.return_temperature()) > 0.0001)
			CRASH("Pipeline reconciliation changed volume or failed to equalize temperature.")
		if(abs(first.thermal_energy() + second.thermal_energy() - energy) > 0.1)
			CRASH("Pipeline reconciliation failed energy conservation.")
		first.clear()
		second.clear()
		first.set_volume(0)
		second.set_volume(0)
		if(native)
			equalize_all_gases_in_list(mixes)
		else
			dogmos_reconcile_pipeline_mixtures(mixes)
		if(first.total_moles() || second.total_moles())
			CRASH("Empty zero-volume network changed.")
		qdel(first)
		qdel(second)
	for(var/sample in 1 to 3)
		for(var/native in list(FALSE, TRUE))
			var/list/mixes = list()
			for(var/index in 1 to 64)
				var/datum/gas_mixture/mix = new(index * 20)
				mix.set_moles(GAS_O2, index)
				mix.set_moles(GAS_N2, index * 2)
				mix.set_temperature(300 + index)
				mixes += mix
			var/started = REALTIMEOFDAY
			for(var/iteration in 1 to 1000)
				if(native)
					equalize_all_gases_in_list(mixes)
				else
					dogmos_reconcile_pipeline_mixtures(mixes)
			var/elapsed = (REALTIMEOFDAY - started + 24 HOURS) % (24 HOURS)
			file("[GLOB.log_directory]/reconcile-measurements.jsonl") << json_encode(list("sample" = sample, "native" = native, "iterations" = 1000, "mixtures" = 64, "elapsed_ms" = elapsed * 100))
			for(var/datum/gas_mixture/mix as anything in mixes)
				qdel(mix)
