#define DOGMOS_REQUIRED_PROTOCOL_VERSION 16
#define DOGMOS_JOB_ACCEPTED 1
#define DOGMOS_JOB_RUNNING 2
#define DOGMOS_JOB_READY 3
#define DOGMOS_JOB_RETRYING 4
#define DOGMOS_JOB_DONE 5
#define DOGMOS_JOB_QUANTUM_US 500
#define DOGMOS_MAX_EXACT_INTEGER 16777216
// Process-metrics layout and availability definitions are generated in dogmos_bindings.dm.
#define DOGMOS_CALLBACK_BATCH_SIZE 256
#define DOGMOS_CALLBACK_SCOPE_GENERAL 1
#define DOGMOS_CALLBACK_SCOPE_REACTION 2
#define DOGMOS_TURF_BATCH_OPERATIONS 512
#define DOGMOS_MIXTURE_CACHE_BUCKETS 2048
// A prefetch cannot usefully load more mixtures than the snapshot cache has buckets: the cache is
// direct-mapped, so anything past that is guaranteed to evict something the same prefetch just
// stored. Capped here rather than at the service, which will happily return far more.
#define DOGMOS_MIXTURE_PREFETCH_LIMIT DOGMOS_MIXTURE_CACHE_BUCKETS
// The production IPC reply window is 64 KiB: 4 count bytes plus 172 bytes
// per compact snapshot. floor((65536 - 4) / 172) = 381 records per call.
#define DOGMOS_MIXTURE_SNAPSHOT_BATCH_LIMIT 381
// Mirrors dogmos-core's DEFAULT_MIXTURE_VOLUME_LITERS. A freshly registered mixture already has
// this volume on the service side.
#define DOGMOS_DEFAULT_MIXTURE_VOLUME 2500
// Mirrors Rust's MINIMUM_MOLES_DELTA_TO_MOVE (world.rs) exactly, as its own constant rather than
// reusing DM's similarly-named MINIMUM_MOLES_DELTA_TO_MOVE (atmos_core.dm) - that one is a
// derived, independently-tunable formula (MOLES_CELLSTANDARD * MINIMUM_AIR_RATIO_TO_MOVE) that
// does not evaluate to the same value. compare() must match Rust's threshold exactly, not DM's.
#define DOGMOS_COMPARE_MINIMUM_MOLES_DELTA 0.01032637
#define DOGMOS_COMPARE_MINIMUM_TEMPERATURE_DELTA 4.0

#define DOGMOS_LIFECYCLE_REGISTER 1
#define DOGMOS_LIFECYCLE_UNREGISTER 2

#define DOGMOS_RESPONSE_APPLIED 1
#define DOGMOS_RESPONSE_SCALAR 2
#define DOGMOS_RESPONSE_SCALARS 3
#define DOGMOS_RESPONSE_BOOLEAN 4
#define DOGMOS_RESPONSE_REACTION_PROGRESS 5

#define DOGMOS_COMMAND_SET_MOLES 1
#define DOGMOS_COMMAND_ADJUST_MOLES 2
#define DOGMOS_COMMAND_ADJUST_MOLES_TEMPERATURE 3
#define DOGMOS_COMMAND_GET_MOLES 4
#define DOGMOS_COMMAND_TEMPERATURE 5
#define DOGMOS_COMMAND_VOLUME 6
#define DOGMOS_COMMAND_HEAT_CAPACITY 7
#define DOGMOS_COMMAND_PARTIAL_HEAT_CAPACITY 8
#define DOGMOS_COMMAND_TOTAL_MOLES 9
#define DOGMOS_COMMAND_PRESSURE 10
#define DOGMOS_COMMAND_THERMAL_ENERGY 11
#define DOGMOS_COMMAND_GET_MOLES_BY_FLAGS 12
#define DOGMOS_COMMAND_BURNABILITY 13
#define DOGMOS_COMMAND_SET_TEMPERATURE 14
#define DOGMOS_COMMAND_SET_VOLUME 15
#define DOGMOS_COMMAND_SET_MINIMUM_HEAT_CAPACITY 16
#define DOGMOS_COMMAND_CLEAR 17
#define DOGMOS_COMMAND_ADD 18
#define DOGMOS_COMMAND_MULTIPLY 19
#define DOGMOS_COMMAND_COPY_FROM 20
#define DOGMOS_COMMAND_ADJUST_HEAT 21
#define DOGMOS_COMMAND_COMPARE 22
#define DOGMOS_COMMAND_EQUALIZE_WITH 23
#define DOGMOS_COMMAND_TEMPERATURE_SHARE 24
#define DOGMOS_COMMAND_TEMPERATURE_SHARE_NON_GAS 25
#define DOGMOS_COMMAND_MARK_IMMUTABLE 26
#define DOGMOS_COMMAND_IS_IMMUTABLE 27
#define DOGMOS_COMMAND_MERGE 28
#define DOGMOS_COMMAND_REMOVE_RATIO_INTO 29
#define DOGMOS_COMMAND_REMOVE_AMOUNT_INTO 30
#define DOGMOS_COMMAND_TRANSFER_GASES 31
#define DOGMOS_COMMAND_TRANSFER_AMOUNT 32
#define DOGMOS_COMMAND_TRANSFER_RATIO 33
#define DOGMOS_COMMAND_TRANSFER_BY_FLAGS 34
#define DOGMOS_COMMAND_SHARE_RATIO 35
#define DOGMOS_COMMAND_REACT 36
#define DOGMOS_COMMAND_CREATE_FROM_SOURCE 37

#define DOGMOS_CALLBACK_REACTION_FINISHED 2
#define DOGMOS_CALLBACK_PRESSURE_DIFFERENCE 3
#define DOGMOS_CALLBACK_DECOMPRESSION_FLOOR_RIP 4
#define DOGMOS_CALLBACK_FIRELOCK_CONSIDERATION 5
#define DOGMOS_CALLBACK_TURF_DESTRUCTION_REQUEST 6
#define DOGMOS_CALLBACK_RUN_DM_REACTION 7
#define DOGMOS_CALLBACK_REACTION_PROFILED 8

#define DOGMOS_TURF_DESTRUCTION_SUPERCONDUCTIVE_HEAT 1

#define DOGMOS_REACTION_PLASMA 1
#define DOGMOS_REACTION_HYDROGEN 2
#define DOGMOS_REACTION_TRITIUM 3
#define DOGMOS_REACTION_FREON 4

#define DOGMOS_SIMULATION_EXCITED_GROUPS 1
#define DOGMOS_SIMULATION_TURF_EQUALIZE 2
#define DOGMOS_SIMULATION_TURF_HEAT 3
#define DOGMOS_SIMULATION_TURFS 4
#define DOGMOS_SIMULATION_REACTIONS 5
#define DOGMOS_STAGE_FULL_BUDGET_MS 1
