//THIS FILE IS AUTOMATICALLY GENERATED BY DOGMOS, PLEASE DO NOT TOUCH IT
//PROC DEFINITIONS MAY MOVE AROUND, THIS IS NORMAL

#define DOGMOS (world.system_type == UNIX ? "libdogmos" : "dogmos")

/proc/dogmos_abi_version()
	return call_ext(DOGMOS, "byond:dogmos_abi_version_ffi")()

/proc/dogmos_callback_drain(fields)
	return call_ext(DOGMOS, "byond:dogmos_callback_drain_ffi")(fields)

/proc/dogmos_continuation_adjust_multiple(fields)
	return call_ext(DOGMOS, "byond:dogmos_continuation_adjust_multiple_ffi")(fields)

/proc/dogmos_continuation_cancel(fields)
	return call_ext(DOGMOS, "byond:dogmos_continuation_cancel_ffi")(fields)

/proc/dogmos_continuation_command(fields)
	return call_ext(DOGMOS, "byond:dogmos_continuation_command_ffi")(fields)

/proc/dogmos_continuation_resume(fields)
	return call_ext(DOGMOS, "byond:dogmos_continuation_resume_ffi")(fields)

/proc/dogmos_feature_fingerprint()
	return call_ext(DOGMOS, "byond:dogmos_feature_fingerprint_ffi")()

/proc/dogmos_frontier_add(records)
	return call_ext(DOGMOS, "byond:dogmos_frontier_add_ffi")(records)

/proc/dogmos_frontier_append(records)
	return call_ext(DOGMOS, "byond:dogmos_frontier_append_ffi")(records)

/proc/dogmos_frontier_begin(fields)
	return call_ext(DOGMOS, "byond:dogmos_frontier_begin_ffi")(fields)

/proc/dogmos_frontier_commit(fields)
	return call_ext(DOGMOS, "byond:dogmos_frontier_commit_ffi")(fields)

/proc/dogmos_frontier_remove(records)
	return call_ext(DOGMOS, "byond:dogmos_frontier_remove_ffi")(records)

/proc/dogmos_gas_metadata_install(numeric_records, keys, names, product_records)
	return call_ext(DOGMOS, "byond:dogmos_gas_metadata_install_ffi")(numeric_records, keys, names, product_records)

/proc/dogmos_mixture_adjust_multiple(fields)
	return call_ext(DOGMOS, "byond:dogmos_mixture_adjust_multiple_ffi")(fields)

/proc/dogmos_mixture_command(fields)
	return call_ext(DOGMOS, "byond:dogmos_mixture_command_ffi")(fields)

/proc/dogmos_mixture_lifecycle_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_mixture_lifecycle_batch_ffi")(entries)

/proc/dogmos_mixture_snapshot(fields)
	return call_ext(DOGMOS, "byond:dogmos_mixture_snapshot_ffi")(fields)

/proc/dogmos_mixture_snapshot_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_mixture_snapshot_batch_ffi")(entries)

/proc/dogmos_mixture_state_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_mixture_state_batch_ffi")(entries)

/proc/dogmos_pipenet_reconcile(entries)
	return call_ext(DOGMOS, "byond:dogmos_pipenet_reconcile_ffi")(entries)

/proc/dogmos_process_metrics()
	return call_ext(DOGMOS, "byond:dogmos_process_metrics_ffi")()

/proc/dogmos_protocol_version()
	return call_ext(DOGMOS, "byond:dogmos_protocol_version_ffi")()

/proc/dogmos_reaction_metadata_install(numeric_records, keys, requirement_records)
	return call_ext(DOGMOS, "byond:dogmos_reaction_metadata_install_ffi")(numeric_records, keys, requirement_records)

/proc/dogmos_service_health()
	return call_ext(DOGMOS, "byond:dogmos_service_health_ffi")()

/proc/dogmos_service_pid()
	return call_ext(DOGMOS, "byond:dogmos_service_pid_ffi")()

/proc/dogmos_service_shutdown()
	return call_ext(DOGMOS, "byond:dogmos_service_shutdown_ffi")()

/proc/dogmos_service_start(service_path)
	return call_ext(DOGMOS, "byond:dogmos_service_start_ffi")(service_path)

/proc/dogmos_service_telemetry()
	return call_ext(DOGMOS, "byond:dogmos_service_telemetry_ffi")()

/proc/dogmos_service_world_generation()
	return call_ext(DOGMOS, "byond:dogmos_service_world_generation_ffi")()

/proc/dogmos_simulation_stage(fields)
	return call_ext(DOGMOS, "byond:dogmos_simulation_stage_ffi")(fields)

/proc/dogmos_source_revision()
	return call_ext(DOGMOS, "byond:dogmos_source_revision_ffi")()

/proc/dogmos_stage_job_cancel(fields)
	return call_ext(DOGMOS, "byond:dogmos_stage_job_cancel_ffi")(fields)

/proc/dogmos_stage_job_commit(fields)
	return call_ext(DOGMOS, "byond:dogmos_stage_job_commit_ffi")(fields)

/proc/dogmos_stage_job_poll(fields)
	return call_ext(DOGMOS, "byond:dogmos_stage_job_poll_ffi")(fields)

/proc/dogmos_stage_job_submit(fields)
	return call_ext(DOGMOS, "byond:dogmos_stage_job_submit_ffi")(fields)

/proc/dogmos_turf_adjacency_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_turf_adjacency_batch_ffi")(entries)

/proc/dogmos_turf_heat_adjacency_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_turf_heat_adjacency_batch_ffi")(entries)

/proc/dogmos_turf_heat_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_turf_heat_batch_ffi")(entries)

/proc/dogmos_turf_heat_snapshot(fields)
	return call_ext(DOGMOS, "byond:dogmos_turf_heat_snapshot_ffi")(fields)

/proc/dogmos_turf_lifecycle_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_turf_lifecycle_batch_ffi")(entries)

/*
 * Generated process-metrics DM adapter reference.
 * Authority: dogmos-byond/src/process_metrics_layout.rs; regenerate with generate_bindings.
 * /proc/dogmos_process_metrics returns 28 exact u16 words in an f32 list.
 * Scalar words are low-first; positions below are one-based DM list indices.
 * Unknown availability bits are rejected; an unavailable counter must be zero.
 * Words 1-2 (u32): DOGMOS_PROCESS_LAYOUT_WORD - Adapter layout version (must match DOGMOS_PROCESS_METRICS_LAYOUT_VERSION).
 * Words 3-4 (u32): DOGMOS_PROCESS_HOST_FLAGS_WORD - DreamDaemon availability flags; host CPU is not included in this adapter.
 * Words 5-6 (u32): DOGMOS_PROCESS_SERVICE_FLAGS_WORD - dogmosd availability flags, independent of DreamDaemon flags.
 * Words 7-8 (u32): DOGMOS_PROCESS_RESERVED_WORD - Reserved; must be zero.
 * Words 9-12 (u64): DOGMOS_PROCESS_HOST_PRIVATE_BYTES_WORD - DreamDaemon private/committed bytes (platform sampler semantics).
 * Words 13-16 (u64): DOGMOS_PROCESS_HOST_VIRTUAL_BYTES_WORD - DreamDaemon virtual address-space bytes.
 * Words 17-20 (u64): DOGMOS_PROCESS_HOST_WORKING_SET_BYTES_WORD - DreamDaemon working-set/resident bytes.
 * Words 21-24 (u64): DOGMOS_PROCESS_SERVICE_RSS_BYTES_WORD - dogmosd resident bytes; never added to DreamDaemon memory.
 * Words 25-28 (u64): DOGMOS_PROCESS_SERVICE_CPU_MILLISECONDS_WORD - dogmosd cumulative CPU milliseconds (not elapsed wall time).
 */
#define DOGMOS_PROCESS_METRICS_WORDS 28
#define DOGMOS_PROCESS_METRICS_LAYOUT_VERSION 1
#define DOGMOS_PROCESS_WORD_BASE 65536
#define DOGMOS_PROCESS_WORD_MAX 65535
#define DOGMOS_PROCESS_LAYOUT_WORD 1
#define DOGMOS_PROCESS_HOST_FLAGS_WORD 3
#define DOGMOS_PROCESS_SERVICE_FLAGS_WORD 5
#define DOGMOS_PROCESS_RESERVED_WORD 7
#define DOGMOS_PROCESS_HOST_PRIVATE_BYTES_WORD 9
#define DOGMOS_PROCESS_HOST_VIRTUAL_BYTES_WORD 13
#define DOGMOS_PROCESS_HOST_WORKING_SET_BYTES_WORD 17
#define DOGMOS_PROCESS_SERVICE_RSS_BYTES_WORD 21
#define DOGMOS_PROCESS_SERVICE_CPU_MILLISECONDS_WORD 25
#define DOGMOS_DREAMDAEMON_PRIVATE_BYTES_AVAILABLE 1
#define DOGMOS_DREAMDAEMON_VIRTUAL_BYTES_AVAILABLE 2
#define DOGMOS_DREAMDAEMON_WORKING_SET_BYTES_AVAILABLE 4
#define DOGMOS_DREAMDAEMON_ALL_AVAILABLE 7
#define DOGMOS_SERVICE_RSS_BYTES_AVAILABLE 1
#define DOGMOS_SERVICE_CPU_MILLISECONDS_AVAILABLE 2
#define DOGMOS_SERVICE_ALL_AVAILABLE 3

// Generated DM adapter layouts. Do not edit. Positions are one-based; widths count list elements.
// u16 words encode unsigned integers little-endian. Finite scalars retain existing domain validation.
// No implicit padding or new version fields; the matched ABI/protocol contract selects these legacy shapes.

#define DOGMOS_DM_HANDLE_FIELDS 2
// SLOT: exact unsigned integer, 0..16777216; identity; slot. Width 1 (through field 1).
#define DOGMOS_DM_HANDLE_SLOT 1
// GENERATION: exact unsigned integer, 0..16777216; identity; generation. Width 1 (through field 2).
#define DOGMOS_DM_HANDLE_GENERATION 2

#define DOGMOS_DM_WORD_HANDLE_FIELDS 4
// SLOT: exact u16 words, 0..65535 each; identity; slot. Width 2 (through field 2).
#define DOGMOS_DM_WORD_HANDLE_SLOT 1
// GENERATION: exact u16 words, 0..65535 each; identity; generation. Width 2 (through field 4).
#define DOGMOS_DM_WORD_HANDLE_GENERATION 3

#define DOGMOS_DM_MIXTURE_COMMAND_FIELDS 11
// KIND: enum/tag, existing protocol values; kind; kind. Width 1 (through field 1).
#define DOGMOS_DM_MIXTURE_COMMAND_KIND 1
// FLAGS: exact u16 bit flags; flags; flags. Width 1 (through field 2).
#define DOGMOS_DM_MIXTURE_COMMAND_FLAGS 2
// PRIMARY_SLOT: exact unsigned integer, 0..16777216; identity; primary slot. Width 1 (through field 3).
#define DOGMOS_DM_MIXTURE_COMMAND_PRIMARY_SLOT 3
// PRIMARY_GENERATION: exact unsigned integer, 0..16777216; identity; primary generation. Width 1 (through field 4).
#define DOGMOS_DM_MIXTURE_COMMAND_PRIMARY_GENERATION 4
// SECONDARY_SLOT: exact unsigned integer, 0..16777216; identity; secondary slot. Width 1 (through field 5).
#define DOGMOS_DM_MIXTURE_COMMAND_SECONDARY_SLOT 5
// SECONDARY_GENERATION: exact unsigned integer, 0..16777216; identity; secondary generation. Width 1 (through field 6).
#define DOGMOS_DM_MIXTURE_COMMAND_SECONDARY_GENERATION 6
// SCALARS: finite scalar, protocol domain validated; operation-dependent; Three existing operation operands; no coefficient changes. Width 3 (through field 9).
#define DOGMOS_DM_MIXTURE_COMMAND_SCALARS 7
// GAS_ID: exact u16; gas id; gas id. Width 1 (through field 10).
#define DOGMOS_DM_MIXTURE_COMMAND_GAS_ID 10
// AUX: exact unsigned integer, 0..16777216; operation-dependent; aux. Width 1 (through field 11).
#define DOGMOS_DM_MIXTURE_COMMAND_AUX 11

#define DOGMOS_DM_MIXTURE_RESPONSE_FIELDS 4
// KIND: enum/tag, existing protocol values; kind; kind. Width 1 (through field 1).
#define DOGMOS_DM_MIXTURE_RESPONSE_KIND 1
// FIRST: finite scalar, protocol domain validated; operation-dependent; first. Width 1 (through field 2).
#define DOGMOS_DM_MIXTURE_RESPONSE_FIRST 2
// SECOND: finite scalar, protocol domain validated; operation-dependent; second. Width 1 (through field 3).
#define DOGMOS_DM_MIXTURE_RESPONSE_SECOND 3
// THIRD: finite scalar, protocol domain validated; operation-dependent; third. Width 1 (through field 4).
#define DOGMOS_DM_MIXTURE_RESPONSE_THIRD 4

#define DOGMOS_DM_REACTION_RESPONSE_FIELDS 8
// KIND: enum/tag, existing protocol values; kind; kind. Width 1 (through field 1).
#define DOGMOS_DM_REACTION_RESPONSE_KIND 1
// FLAGS: exact unsigned integer, 0..16777216; count; flags. Width 1 (through field 2).
#define DOGMOS_DM_REACTION_RESPONSE_FLAGS 2
// WORK_ITEMS: exact unsigned integer, 0..16777216; count; work items. Width 1 (through field 3).
#define DOGMOS_DM_REACTION_RESPONSE_WORK_ITEMS 3
// PENDING: boolean, 0 or 1; flag; pending. Width 1 (through field 4).
#define DOGMOS_DM_REACTION_RESPONSE_PENDING 4
// TRANSACTION: exact u16 words, 0..65535 each; identity; transaction. Width 4 (through field 8).
#define DOGMOS_DM_REACTION_RESPONSE_TRANSACTION 5

#define DOGMOS_DM_ADJUSTMENT_FIELDS 2
// GAS_ID: exact u16; gas id; gas id. Width 1 (through field 1).
#define DOGMOS_DM_ADJUSTMENT_GAS_ID 1
// DELTA: finite scalar, protocol domain validated; moles; delta. Width 1 (through field 2).
#define DOGMOS_DM_ADJUSTMENT_DELTA 2

#define DOGMOS_DM_MIXTURE_LIFECYCLE_FIELDS 3
// ACTION: enum/tag, existing protocol values; kind; action. Width 1 (through field 1).
#define DOGMOS_DM_MIXTURE_LIFECYCLE_ACTION 1
// SLOT: exact unsigned integer, 0..16777216; identity; slot. Width 1 (through field 2).
#define DOGMOS_DM_MIXTURE_LIFECYCLE_SLOT 2
// GENERATION: exact unsigned integer, 0..16777216; identity; generation. Width 1 (through field 3).
#define DOGMOS_DM_MIXTURE_LIFECYCLE_GENERATION 3

#define DOGMOS_DM_MIXTURE_STATE_FIELDS 38
// SLOT: exact unsigned integer, 0..16777216; identity; slot. Width 1 (through field 1).
#define DOGMOS_DM_MIXTURE_STATE_SLOT 1
// GENERATION: exact unsigned integer, 0..16777216; identity; generation. Width 1 (through field 2).
#define DOGMOS_DM_MIXTURE_STATE_GENERATION 2
// REVISION: exact u16 words, 0..65535 each; identity; revision. Width 2 (through field 4).
#define DOGMOS_DM_MIXTURE_STATE_REVISION 3
// TEMPERATURE: finite scalar, protocol domain validated; kelvin; temperature. Width 1 (through field 5).
#define DOGMOS_DM_MIXTURE_STATE_TEMPERATURE 5
// VOLUME: finite scalar, protocol domain validated; liters; volume. Width 1 (through field 6).
#define DOGMOS_DM_MIXTURE_STATE_VOLUME 6
// GASES: finite scalar, protocol domain validated; moles; gases. Width 32 (through field 38).
#define DOGMOS_DM_MIXTURE_STATE_GASES 7

#define DOGMOS_DM_MIXTURE_SNAPSHOT_FIELDS 42
// REVISION: exact u16 words, 0..65535 each; identity; revision. Width 2 (through field 2).
#define DOGMOS_DM_MIXTURE_SNAPSHOT_REVISION 1
// GAS_COUNT: exact unsigned integer, 0..16777216; count; gas count. Width 1 (through field 3).
#define DOGMOS_DM_MIXTURE_SNAPSHOT_GAS_COUNT 3
// TEMPERATURE: finite scalar, protocol domain validated; kelvin; temperature. Width 1 (through field 4).
#define DOGMOS_DM_MIXTURE_SNAPSHOT_TEMPERATURE 4
// VOLUME: finite scalar, protocol domain validated; liters; volume. Width 1 (through field 5).
#define DOGMOS_DM_MIXTURE_SNAPSHOT_VOLUME 5
// MINIMUM_HEAT_CAPACITY: finite scalar, protocol domain validated; joules/kelvin; minimum heat capacity. Width 1 (through field 6).
#define DOGMOS_DM_MIXTURE_SNAPSHOT_MINIMUM_HEAT_CAPACITY 6
// TOTAL_MOLES: finite scalar, protocol domain validated; moles; total moles. Width 1 (through field 7).
#define DOGMOS_DM_MIXTURE_SNAPSHOT_TOTAL_MOLES 7
// PRESSURE: finite scalar, protocol domain validated; kilopascals; pressure. Width 1 (through field 8).
#define DOGMOS_DM_MIXTURE_SNAPSHOT_PRESSURE 8
// HEAT_CAPACITY: finite scalar, protocol domain validated; joules/kelvin; heat capacity. Width 1 (through field 9).
#define DOGMOS_DM_MIXTURE_SNAPSHOT_HEAT_CAPACITY 9
// IMMUTABLE: boolean, 0 or 1; flag; immutable. Width 1 (through field 10).
#define DOGMOS_DM_MIXTURE_SNAPSHOT_IMMUTABLE 10
// GASES: finite scalar, protocol domain validated; moles; Fixed gas-id-indexed slots; unused slots retain protocol zeros. Width 32 (through field 42).
#define DOGMOS_DM_MIXTURE_SNAPSHOT_GASES 11

#define DOGMOS_DM_PIPENET_RECORD_FIELDS 44
// SLOT: exact unsigned integer, 0..16777216; identity; slot. Width 1 (through field 1).
#define DOGMOS_DM_PIPENET_RECORD_SLOT 1
// GENERATION: exact unsigned integer, 0..16777216; identity; generation. Width 1 (through field 2).
#define DOGMOS_DM_PIPENET_RECORD_GENERATION 2
// SNAPSHOT: mixture_snapshot record; record; Same snapshot layout follows handle. Width 42 (through field 44).
#define DOGMOS_DM_PIPENET_RECORD_SNAPSHOT 3

#define DOGMOS_DM_GAS_METADATA_FIELDS 13
// ID: exact u16; gas id; id. Width 1 (through field 1).
#define DOGMOS_DM_GAS_METADATA_ID 1
// FLAGS: exact u16 words, 0..65535 each; flags; flags. Width 2 (through field 3).
#define DOGMOS_DM_GAS_METADATA_FLAGS 2
// SPECIFIC_HEAT: finite scalar, protocol domain validated; joules/(mole kelvin); specific heat. Width 1 (through field 4).
#define DOGMOS_DM_GAS_METADATA_SPECIFIC_HEAT 4
// FUSION_POWER: finite scalar, protocol domain validated; existing fusion units; fusion power. Width 1 (through field 5).
#define DOGMOS_DM_GAS_METADATA_FUSION_POWER 5
// MOLES_VISIBLE_PRESENT: boolean, 0 or 1; flag; moles visible present. Width 1 (through field 6).
#define DOGMOS_DM_GAS_METADATA_MOLES_VISIBLE_PRESENT 6
// MOLES_VISIBLE: finite scalar, protocol domain validated; moles; Zero when absent. Width 1 (through field 7).
#define DOGMOS_DM_GAS_METADATA_MOLES_VISIBLE 7
// ENTHALPY: finite scalar, protocol domain validated; existing energy units; enthalpy. Width 1 (through field 8).
#define DOGMOS_DM_GAS_METADATA_ENTHALPY 8
// FIRE_RADIATION: finite scalar, protocol domain validated; existing radiation units; fire radiation. Width 1 (through field 9).
#define DOGMOS_DM_GAS_METADATA_FIRE_RADIATION 9
// FIRE_ROLE: enum/tag, existing protocol values; kind; fire role. Width 1 (through field 10).
#define DOGMOS_DM_GAS_METADATA_FIRE_ROLE 10
// FIRE_MINIMUM_TEMPERATURE: finite scalar, protocol domain validated; kelvin; fire minimum temperature. Width 1 (through field 11).
#define DOGMOS_DM_GAS_METADATA_FIRE_MINIMUM_TEMPERATURE 11
// FIRE_POWER_OR_RATE: finite scalar, protocol domain validated; role-dependent; fire power or rate. Width 1 (through field 12).
#define DOGMOS_DM_GAS_METADATA_FIRE_POWER_OR_RATE 12
// PRODUCT_KIND: enum/tag, existing protocol values; kind; product kind. Width 1 (through field 13).
#define DOGMOS_DM_GAS_METADATA_PRODUCT_KIND 13

#define DOGMOS_DM_GAS_PRODUCT_FIELDS 3
// OWNER: exact unsigned integer, 0..16777216; zero-based metadata record index; owner. Width 1 (through field 1).
#define DOGMOS_DM_GAS_PRODUCT_OWNER 1
// GAS_ID: exact u16; gas id; gas id. Width 1 (through field 2).
#define DOGMOS_DM_GAS_PRODUCT_GAS_ID 2
// RATIO: finite scalar, protocol domain validated; ratio; ratio. Width 1 (through field 3).
#define DOGMOS_DM_GAS_PRODUCT_RATIO 3

#define DOGMOS_DM_REACTION_METADATA_FIELDS 12
// ID: exact u16 words, 0..65535 each; identity; id. Width 2 (through field 2).
#define DOGMOS_DM_REACTION_METADATA_ID 1
// EXECUTION: enum/tag, existing protocol values; kind; execution. Width 1 (through field 3).
#define DOGMOS_DM_REACTION_METADATA_EXECUTION 3
// PRIORITY: finite scalar, protocol domain validated; ordering; priority. Width 1 (through field 4).
#define DOGMOS_DM_REACTION_METADATA_PRIORITY 4
// MINIMUM_TEMPERATURE_PRESENT: boolean, 0 or 1; flag; minimum temperature present. Width 1 (through field 5).
#define DOGMOS_DM_REACTION_METADATA_MINIMUM_TEMPERATURE_PRESENT 5
// MINIMUM_TEMPERATURE: finite scalar, protocol domain validated; kelvin; Zero when absent. Width 1 (through field 6).
#define DOGMOS_DM_REACTION_METADATA_MINIMUM_TEMPERATURE 6
// MAXIMUM_TEMPERATURE_PRESENT: boolean, 0 or 1; flag; maximum temperature present. Width 1 (through field 7).
#define DOGMOS_DM_REACTION_METADATA_MAXIMUM_TEMPERATURE_PRESENT 7
// MAXIMUM_TEMPERATURE: finite scalar, protocol domain validated; kelvin; Zero when absent. Width 1 (through field 8).
#define DOGMOS_DM_REACTION_METADATA_MAXIMUM_TEMPERATURE 8
// MINIMUM_ENERGY_PRESENT: boolean, 0 or 1; flag; minimum energy present. Width 1 (through field 9).
#define DOGMOS_DM_REACTION_METADATA_MINIMUM_ENERGY_PRESENT 9
// MINIMUM_ENERGY: finite scalar, protocol domain validated; joules; Zero when absent. Width 1 (through field 10).
#define DOGMOS_DM_REACTION_METADATA_MINIMUM_ENERGY 10
// MINIMUM_FIRE_REAGENTS_PRESENT: boolean, 0 or 1; flag; minimum fire reagents present. Width 1 (through field 11).
#define DOGMOS_DM_REACTION_METADATA_MINIMUM_FIRE_REAGENTS_PRESENT 11
// MINIMUM_FIRE_REAGENTS: finite scalar, protocol domain validated; moles; Zero when absent. Width 1 (through field 12).
#define DOGMOS_DM_REACTION_METADATA_MINIMUM_FIRE_REAGENTS 12

#define DOGMOS_DM_REACTION_REQUIREMENT_FIELDS 3
// OWNER: exact unsigned integer, 0..16777216; zero-based metadata record index; owner. Width 1 (through field 1).
#define DOGMOS_DM_REACTION_REQUIREMENT_OWNER 1
// GAS_ID: exact u16; gas id; gas id. Width 1 (through field 2).
#define DOGMOS_DM_REACTION_REQUIREMENT_GAS_ID 2
// MINIMUM_MOLES: finite scalar, protocol domain validated; moles; minimum moles. Width 1 (through field 3).
#define DOGMOS_DM_REACTION_REQUIREMENT_MINIMUM_MOLES 3

#define DOGMOS_DM_TURF_LIFECYCLE_FIELDS 6
// ACTION: enum/tag, existing protocol values; kind; action. Width 1 (through field 1).
#define DOGMOS_DM_TURF_LIFECYCLE_ACTION 1
// SLOT: exact unsigned integer, 0..16777216; identity; slot. Width 1 (through field 2).
#define DOGMOS_DM_TURF_LIFECYCLE_SLOT 2
// GENERATION: exact unsigned integer, 0..16777216; identity; generation. Width 1 (through field 3).
#define DOGMOS_DM_TURF_LIFECYCLE_GENERATION 3
// MIXTURE_PRESENT: boolean, 0 or 1; flag; mixture present. Width 1 (through field 4).
#define DOGMOS_DM_TURF_LIFECYCLE_MIXTURE_PRESENT 4
// MIXTURE_SLOT: exact unsigned integer, 0..16777216; identity; mixture slot. Width 1 (through field 5).
#define DOGMOS_DM_TURF_LIFECYCLE_MIXTURE_SLOT 5
// MIXTURE_GENERATION: exact unsigned integer, 0..16777216; identity; mixture generation. Width 1 (through field 6).
#define DOGMOS_DM_TURF_LIFECYCLE_MIXTURE_GENERATION 6

#define DOGMOS_DM_TURF_ADJACENCY_FIELDS 6
// LEFT_SLOT: exact unsigned integer, 0..16777216; identity; left slot. Width 1 (through field 1).
#define DOGMOS_DM_TURF_ADJACENCY_LEFT_SLOT 1
// LEFT_GENERATION: exact unsigned integer, 0..16777216; identity; left generation. Width 1 (through field 2).
#define DOGMOS_DM_TURF_ADJACENCY_LEFT_GENERATION 2
// RIGHT_SLOT: exact unsigned integer, 0..16777216; identity; right slot. Width 1 (through field 3).
#define DOGMOS_DM_TURF_ADJACENCY_RIGHT_SLOT 3
// RIGHT_GENERATION: exact unsigned integer, 0..16777216; identity; right generation. Width 1 (through field 4).
#define DOGMOS_DM_TURF_ADJACENCY_RIGHT_GENERATION 4
// CONNECTED: boolean, 0 or 1; flag; connected. Width 1 (through field 5).
#define DOGMOS_DM_TURF_ADJACENCY_CONNECTED 5
// FIRELOCK: boolean, 0 or 1; flag; firelock. Width 1 (through field 6).
#define DOGMOS_DM_TURF_ADJACENCY_FIRELOCK 6

#define DOGMOS_DM_TURF_HEAT_ADJACENCY_FIELDS 5
// LEFT_SLOT: exact unsigned integer, 0..16777216; identity; left slot. Width 1 (through field 1).
#define DOGMOS_DM_TURF_HEAT_ADJACENCY_LEFT_SLOT 1
// LEFT_GENERATION: exact unsigned integer, 0..16777216; identity; left generation. Width 1 (through field 2).
#define DOGMOS_DM_TURF_HEAT_ADJACENCY_LEFT_GENERATION 2
// RIGHT_SLOT: exact unsigned integer, 0..16777216; identity; right slot. Width 1 (through field 3).
#define DOGMOS_DM_TURF_HEAT_ADJACENCY_RIGHT_SLOT 3
// RIGHT_GENERATION: exact unsigned integer, 0..16777216; identity; right generation. Width 1 (through field 4).
#define DOGMOS_DM_TURF_HEAT_ADJACENCY_RIGHT_GENERATION 4
// CONNECTED: boolean, 0 or 1; flag; connected. Width 1 (through field 5).
#define DOGMOS_DM_TURF_HEAT_ADJACENCY_CONNECTED 5

#define DOGMOS_DM_TURF_HEAT_FIELDS 7
// SLOT: exact unsigned integer, 0..16777216; identity; slot. Width 1 (through field 1).
#define DOGMOS_DM_TURF_HEAT_SLOT 1
// GENERATION: exact unsigned integer, 0..16777216; identity; generation. Width 1 (through field 2).
#define DOGMOS_DM_TURF_HEAT_GENERATION 2
// PRESENT: boolean, 0 or 1; flag; present. Width 1 (through field 3).
#define DOGMOS_DM_TURF_HEAT_PRESENT 3
// TEMPERATURE: finite scalar, protocol domain validated; kelvin; temperature. Width 1 (through field 4).
#define DOGMOS_DM_TURF_HEAT_TEMPERATURE 4
// CONDUCTIVITY: finite scalar, protocol domain validated; existing thermal conductivity units; conductivity. Width 1 (through field 5).
#define DOGMOS_DM_TURF_HEAT_CONDUCTIVITY 5
// HEAT_CAPACITY: finite scalar, protocol domain validated; joules/kelvin; heat capacity. Width 1 (through field 6).
#define DOGMOS_DM_TURF_HEAT_HEAT_CAPACITY 6
// ADJACENT_TO_SPACE: boolean, 0 or 1; flag; adjacent to space. Width 1 (through field 7).
#define DOGMOS_DM_TURF_HEAT_ADJACENT_TO_SPACE 7

#define DOGMOS_DM_HEAT_SNAPSHOT_FIELDS 5
// PRESENT: boolean, 0 or 1; flag; present. Width 1 (through field 1).
#define DOGMOS_DM_HEAT_SNAPSHOT_PRESENT 1
// TEMPERATURE: finite scalar, protocol domain validated; kelvin; temperature. Width 1 (through field 2).
#define DOGMOS_DM_HEAT_SNAPSHOT_TEMPERATURE 2
// CONDUCTIVITY: finite scalar, protocol domain validated; existing thermal conductivity units; conductivity. Width 1 (through field 3).
#define DOGMOS_DM_HEAT_SNAPSHOT_CONDUCTIVITY 3
// HEAT_CAPACITY: finite scalar, protocol domain validated; joules/kelvin; heat capacity. Width 1 (through field 4).
#define DOGMOS_DM_HEAT_SNAPSHOT_HEAT_CAPACITY 4
// ADJACENT_TO_SPACE: boolean, 0 or 1; flag; adjacent to space. Width 1 (through field 5).
#define DOGMOS_DM_HEAT_SNAPSHOT_ADJACENT_TO_SPACE 5

#define DOGMOS_DM_CALLBACK_REQUEST_FIELDS 7
// SCOPE: enum/tag, existing protocol values; scope; scope. Width 1 (through field 1).
#define DOGMOS_DM_CALLBACK_REQUEST_SCOPE 1
// TRANSACTION: exact u16 words, 0..65535 each; identity; transaction. Width 4 (through field 5).
#define DOGMOS_DM_CALLBACK_REQUEST_TRANSACTION 2
// MAX_EVENTS: exact u16 words, 0..65535 each; count; max events. Width 2 (through field 7).
#define DOGMOS_DM_CALLBACK_REQUEST_MAX_EVENTS 6

#define DOGMOS_DM_CALLBACK_HEADER_FIELDS 12
// RETURNED: exact u16 words, 0..65535 each; count; returned. Width 2 (through field 2).
#define DOGMOS_DM_CALLBACK_HEADER_RETURNED 1
// REMAINING: exact u16 words, 0..65535 each; count; remaining. Width 2 (through field 4).
#define DOGMOS_DM_CALLBACK_HEADER_REMAINING 3
// CAPACITY: exact u16 words, 0..65535 each; count; capacity. Width 2 (through field 6).
#define DOGMOS_DM_CALLBACK_HEADER_CAPACITY 5
// HIGH_WATER: exact u16 words, 0..65535 each; count; high water. Width 2 (through field 8).
#define DOGMOS_DM_CALLBACK_HEADER_HIGH_WATER 7
// REJECTED: exact u16 words, 0..65535 each; count; rejected. Width 4 (through field 12).
#define DOGMOS_DM_CALLBACK_HEADER_REJECTED 9

#define DOGMOS_DM_CONTINUATION_TOKEN_FIELDS 10
// WORLD_GENERATION: exact u16 words, 0..65535 each; identity; world generation. Width 2 (through field 2).
#define DOGMOS_DM_CONTINUATION_TOKEN_WORLD_GENERATION 1
// ID: exact u16 words, 0..65535 each; identity; id. Width 4 (through field 6).
#define DOGMOS_DM_CONTINUATION_TOKEN_ID 3
// DEADLINE: exact u16 words, 0..65535 each; ticks; deadline. Width 4 (through field 10).
#define DOGMOS_DM_CONTINUATION_TOKEN_DEADLINE 7

#define DOGMOS_DM_CALLBACK_EVENT_FIELDS 36
// SEQUENCE: exact u16 words, 0..65535 each; identity; sequence. Width 4 (through field 4).
#define DOGMOS_DM_CALLBACK_EVENT_SEQUENCE 1
// TRANSACTION: exact u16 words, 0..65535 each; identity; transaction. Width 4 (through field 8).
#define DOGMOS_DM_CALLBACK_EVENT_TRANSACTION 5
// SCOPE: enum/tag, existing protocol values; scope; scope. Width 1 (through field 9).
#define DOGMOS_DM_CALLBACK_EVENT_SCOPE 9
// KIND: enum/tag, existing protocol values; kind; kind. Width 1 (through field 10).
#define DOGMOS_DM_CALLBACK_EVENT_KIND 10
// FLAGS: reserved, zero; flags; flags. Width 1 (through field 11).
#define DOGMOS_DM_CALLBACK_EVENT_FLAGS 11
// SUBJECT_SLOT: exact u16 words, 0..65535 each; identity; subject slot. Width 2 (through field 13).
#define DOGMOS_DM_CALLBACK_EVENT_SUBJECT_SLOT 12
// SUBJECT_GENERATION: exact u16 words, 0..65535 each; identity; subject generation. Width 2 (through field 15).
#define DOGMOS_DM_CALLBACK_EVENT_SUBJECT_GENERATION 14
// TARGET_SLOT: exact u16 words, 0..65535 each; identity; target slot. Width 2 (through field 17).
#define DOGMOS_DM_CALLBACK_EVENT_TARGET_SLOT 16
// TARGET_GENERATION: exact u16 words, 0..65535 each; identity; target generation. Width 2 (through field 19).
#define DOGMOS_DM_CALLBACK_EVENT_TARGET_GENERATION 18
// VALUES: finite scalar, protocol domain validated; event-dependent; values. Width 4 (through field 23).
#define DOGMOS_DM_CALLBACK_EVENT_VALUES 20
// AUX: exact u16 words, 0..65535 each; event-dependent; aux. Width 2 (through field 25).
#define DOGMOS_DM_CALLBACK_EVENT_AUX 24
// TOKEN_PRESENT: boolean, 0 or 1; flag; token present. Width 1 (through field 26).
#define DOGMOS_DM_CALLBACK_EVENT_TOKEN_PRESENT 26
// TOKEN: continuation_token record; record; All-zero token words when absent. Width 10 (through field 36).
#define DOGMOS_DM_CALLBACK_EVENT_TOKEN 27

#define DOGMOS_DM_CONTINUATION_COMMAND_FIELDS 21
// TOKEN: continuation_token record; record; token. Width 10 (through field 10).
#define DOGMOS_DM_CONTINUATION_COMMAND_TOKEN 1
// COMMAND: mixture_command record; record; command. Width 11 (through field 21).
#define DOGMOS_DM_CONTINUATION_COMMAND_COMMAND 11

#define DOGMOS_DM_CONTINUATION_RESUME_FIELDS 11
// TOKEN: continuation_token record; record; token. Width 10 (through field 10).
#define DOGMOS_DM_CONTINUATION_RESUME_TOKEN 1
// REACTION_RESULT: exact unsigned integer, 0..16777216; existing reaction flags; reaction result. Width 1 (through field 11).
#define DOGMOS_DM_CONTINUATION_RESUME_REACTION_RESULT 11

#define DOGMOS_DM_EPOCH_FIELDS 4
// EPOCH: exact u16 words, 0..65535 each; identity; epoch. Width 4 (through field 4).
#define DOGMOS_DM_EPOCH_EPOCH 1

#define DOGMOS_DM_WORD_COUNT_FIELDS 2
// COUNT: exact u16 words, 0..65535 each; count; count. Width 2 (through field 2).
#define DOGMOS_DM_WORD_COUNT_COUNT 1

#define DOGMOS_DM_FRONTIER_BEGIN_FIELDS 6
// EPOCH: exact u16 words, 0..65535 each; identity; epoch. Width 4 (through field 4).
#define DOGMOS_DM_FRONTIER_BEGIN_EPOCH 1
// EXPECTED_COUNT: exact u16 words, 0..65535 each; count; expected count. Width 2 (through field 6).
#define DOGMOS_DM_FRONTIER_BEGIN_EXPECTED_COUNT 5

#define DOGMOS_DM_FRONTIER_APPEND_HEADER_FIELDS 6
// EPOCH: exact u16 words, 0..65535 each; identity; epoch. Width 4 (through field 4).
#define DOGMOS_DM_FRONTIER_APPEND_HEADER_EPOCH 1
// OFFSET: exact u16 words, 0..65535 each; handle count; offset. Width 2 (through field 6).
#define DOGMOS_DM_FRONTIER_APPEND_HEADER_OFFSET 5

#define DOGMOS_DM_FRONTIER_COMMIT_RESPONSE_FIELDS 6
// EPOCH: exact u16 words, 0..65535 each; identity; epoch. Width 4 (through field 4).
#define DOGMOS_DM_FRONTIER_COMMIT_RESPONSE_EPOCH 1
// COUNT: exact u16 words, 0..65535 each; count; count. Width 2 (through field 6).
#define DOGMOS_DM_FRONTIER_COMMIT_RESPONSE_COUNT 5

#define DOGMOS_DM_STAGE_REQUEST_FIELDS 12
// STAGE: enum/tag, existing protocol values; kind; stage. Width 1 (through field 1).
#define DOGMOS_DM_STAGE_REQUEST_STAGE 1
// FRONTIER_EPOCH: exact u16 words, 0..65535 each; identity; frontier epoch. Width 4 (through field 5).
#define DOGMOS_DM_STAGE_REQUEST_FRONTIER_EPOCH 2
// STAGE_EPOCH: exact u16 words, 0..65535 each; identity; stage epoch. Width 4 (through field 9).
#define DOGMOS_DM_STAGE_REQUEST_STAGE_EPOCH 6
// WORK_LIMIT: exact u16 words, 0..65535 each; count; work limit. Width 2 (through field 11).
#define DOGMOS_DM_STAGE_REQUEST_WORK_LIMIT 10
// SECONDS_PER_TICK: finite scalar, protocol domain validated; seconds; seconds per tick. Width 1 (through field 12).
#define DOGMOS_DM_STAGE_REQUEST_SECONDS_PER_TICK 12

#define DOGMOS_DM_STAGE_RESPONSE_FIELDS 13
// WORK_ITEMS: exact u16 words, 0..65535 each; count; work items. Width 2 (through field 2).
#define DOGMOS_DM_STAGE_RESPONSE_WORK_ITEMS 1
// CALLBACK_EVENTS: exact u16 words, 0..65535 each; count; callback events. Width 2 (through field 4).
#define DOGMOS_DM_STAGE_RESPONSE_CALLBACK_EVENTS 3
// PENDING: boolean, 0 or 1; flag; pending. Width 1 (through field 5).
#define DOGMOS_DM_STAGE_RESPONSE_PENDING 5
// REMAINING: exact u16 words, 0..65535 each; count; remaining. Width 2 (through field 7).
#define DOGMOS_DM_STAGE_RESPONSE_REMAINING 6
// EQUALIZE_SEEDS: exact u16 words, 0..65535 each; count; equalize seeds. Width 2 (through field 9).
#define DOGMOS_DM_STAGE_RESPONSE_EQUALIZE_SEEDS 8
// GROUP_SEEDS: exact u16 words, 0..65535 each; count; group seeds. Width 2 (through field 11).
#define DOGMOS_DM_STAGE_RESPONSE_GROUP_SEEDS 10
// HEAT_SEEDS: exact u16 words, 0..65535 each; count; heat seeds. Width 2 (through field 13).
#define DOGMOS_DM_STAGE_RESPONSE_HEAT_SEEDS 12

#define DOGMOS_DM_JOB_SUBMIT_FIELDS 13
// STAGE: enum/tag, existing protocol values; kind; stage. Width 1 (through field 1).
#define DOGMOS_DM_JOB_SUBMIT_STAGE 1
// FRONTIER_EPOCH: exact u16 words, 0..65535 each; identity; frontier epoch. Width 4 (through field 5).
#define DOGMOS_DM_JOB_SUBMIT_FRONTIER_EPOCH 2
// STAGE_EPOCH: exact u16 words, 0..65535 each; identity; stage epoch. Width 4 (through field 9).
#define DOGMOS_DM_JOB_SUBMIT_STAGE_EPOCH 6
// WORK_LIMIT: exact u16 words, 0..65535 each; count; work limit. Width 2 (through field 11).
#define DOGMOS_DM_JOB_SUBMIT_WORK_LIMIT 10
// SECONDS_PER_TICK: finite scalar, protocol domain validated; seconds; seconds per tick. Width 1 (through field 12).
#define DOGMOS_DM_JOB_SUBMIT_SECONDS_PER_TICK 12
// QUANTUM_US: exact unsigned integer, 0..16777216; microseconds; quantum us. Width 1 (through field 13).
#define DOGMOS_DM_JOB_SUBMIT_QUANTUM_US 13

#define DOGMOS_DM_JOB_IDENTITY_FIELDS 4
// JOB: exact u16 words, 0..65535 each; nonzero identity; job. Width 4 (through field 4).
#define DOGMOS_DM_JOB_IDENTITY_JOB 1

#define DOGMOS_DM_JOB_COMMIT_FIELDS 8
// JOB: exact u16 words, 0..65535 each; nonzero identity; job. Width 4 (through field 4).
#define DOGMOS_DM_JOB_COMMIT_JOB 1
// UNIT: exact u16 words, 0..65535 each; nonzero identity; unit. Width 4 (through field 8).
#define DOGMOS_DM_JOB_COMMIT_UNIT 5

#define DOGMOS_DM_JOB_RESPONSE_FIELDS 26
// JOB: exact u16 words, 0..65535 each; identity; job. Width 4 (through field 4).
#define DOGMOS_DM_JOB_RESPONSE_JOB 1
// STATUS: enum/tag, existing protocol values; status; status. Width 1 (through field 5).
#define DOGMOS_DM_JOB_RESPONSE_STATUS 5
// STAGE: enum/tag, existing protocol values; kind; stage. Width 1 (through field 6).
#define DOGMOS_DM_JOB_RESPONSE_STAGE 6
// UNIT: exact u16 words, 0..65535 each; identity; unit. Width 4 (through field 10).
#define DOGMOS_DM_JOB_RESPONSE_UNIT 7
// WORK_ITEMS: exact u16 words, 0..65535 each; count; work items. Width 2 (through field 12).
#define DOGMOS_DM_JOB_RESPONSE_WORK_ITEMS 11
// REMAINING: exact u16 words, 0..65535 each; count; remaining. Width 2 (through field 14).
#define DOGMOS_DM_JOB_RESPONSE_REMAINING 13
// COMMITTED_UNITS: exact u16 words, 0..65535 each; count; committed units. Width 4 (through field 18).
#define DOGMOS_DM_JOB_RESPONSE_COMMITTED_UNITS 15
// EQUALIZE_SEEDS: exact u16 words, 0..65535 each; count; equalize seeds. Width 2 (through field 20).
#define DOGMOS_DM_JOB_RESPONSE_EQUALIZE_SEEDS 19
// GROUP_SEEDS: exact u16 words, 0..65535 each; count; group seeds. Width 2 (through field 22).
#define DOGMOS_DM_JOB_RESPONSE_GROUP_SEEDS 21
// HEAT_SEEDS: exact u16 words, 0..65535 each; count; heat seeds. Width 2 (through field 24).
#define DOGMOS_DM_JOB_RESPONSE_HEAT_SEEDS 23
// CALLBACK_EVENTS: exact u16 words, 0..65535 each; count; callback events. Width 2 (through field 26).
#define DOGMOS_DM_JOB_RESPONSE_CALLBACK_EVENTS 25

#define DOGMOS_DM_SERVICE_TELEMETRY_FIELDS 236
// CALLBACK_DEPTH: exact u16 words, 0..65535 each; count; callback depth. Width 2 (through field 2).
#define DOGMOS_DM_SERVICE_TELEMETRY_CALLBACK_DEPTH 1
// CALLBACK_CAPACITY: exact u16 words, 0..65535 each; count; callback capacity. Width 2 (through field 4).
#define DOGMOS_DM_SERVICE_TELEMETRY_CALLBACK_CAPACITY 3
// CALLBACK_HIGH_WATER: exact u16 words, 0..65535 each; count; callback high water. Width 2 (through field 6).
#define DOGMOS_DM_SERVICE_TELEMETRY_CALLBACK_HIGH_WATER 5
// CONTINUATION_DEPTH: exact u16 words, 0..65535 each; count; continuation depth. Width 2 (through field 8).
#define DOGMOS_DM_SERVICE_TELEMETRY_CONTINUATION_DEPTH 7
// CONTINUATION_CAPACITY: exact u16 words, 0..65535 each; count; continuation capacity. Width 2 (through field 10).
#define DOGMOS_DM_SERVICE_TELEMETRY_CONTINUATION_CAPACITY 9
// CONTINUATION_HIGH_WATER: exact u16 words, 0..65535 each; count; continuation high water. Width 2 (through field 12).
#define DOGMOS_DM_SERVICE_TELEMETRY_CONTINUATION_HIGH_WATER 11
// OLDEST_CALLBACK_AGE: exact u16 words, 0..65535 each; ticks; oldest callback age. Width 4 (through field 16).
#define DOGMOS_DM_SERVICE_TELEMETRY_OLDEST_CALLBACK_AGE 13
// CALLBACK_ENQUEUED: exact u16 words, 0..65535 each; count; callback enqueued. Width 4 (through field 20).
#define DOGMOS_DM_SERVICE_TELEMETRY_CALLBACK_ENQUEUED 17
// CALLBACK_DRAINED: exact u16 words, 0..65535 each; count; callback drained. Width 4 (through field 24).
#define DOGMOS_DM_SERVICE_TELEMETRY_CALLBACK_DRAINED 21
// CALLBACK_REJECTED: exact u16 words, 0..65535 each; count; callback rejected. Width 4 (through field 28).
#define DOGMOS_DM_SERVICE_TELEMETRY_CALLBACK_REJECTED 25
// CONTINUATION_TIMEOUTS: exact u16 words, 0..65535 each; count; continuation timeouts. Width 4 (through field 32).
#define DOGMOS_DM_SERVICE_TELEMETRY_CONTINUATION_TIMEOUTS 29
// REQUEST_TIMEOUTS: exact u16 words, 0..65535 each; count; request timeouts. Width 4 (through field 36).
#define DOGMOS_DM_SERVICE_TELEMETRY_REQUEST_TIMEOUTS 33
// PROTOCOL_ERRORS: exact u16 words, 0..65535 each; count; protocol errors. Width 4 (through field 40).
#define DOGMOS_DM_SERVICE_TELEMETRY_PROTOCOL_ERRORS 37
// ENQUEUED_BY_KIND: exact u16 words, 0..65535 each; per-kind counters; enqueued by kind. Width 32 (through field 72).
#define DOGMOS_DM_SERVICE_TELEMETRY_ENQUEUED_BY_KIND 41
// DRAINED_BY_KIND: exact u16 words, 0..65535 each; per-kind counters; drained by kind. Width 32 (through field 104).
#define DOGMOS_DM_SERVICE_TELEMETRY_DRAINED_BY_KIND 73
// REJECTED_BY_KIND: exact u16 words, 0..65535 each; per-kind counters; rejected by kind. Width 32 (through field 136).
#define DOGMOS_DM_SERVICE_TELEMETRY_REJECTED_BY_KIND 105
// PROCESS_FLAGS: exact u16 words, 0..65535 each; availability flags; process flags. Width 2 (through field 138).
#define DOGMOS_DM_SERVICE_TELEMETRY_PROCESS_FLAGS 137
// RSS: exact u16 words, 0..65535 each; bytes; rss. Width 4 (through field 142).
#define DOGMOS_DM_SERVICE_TELEMETRY_RSS 139
// CPU: exact u16 words, 0..65535 each; milliseconds; cpu. Width 4 (through field 146).
#define DOGMOS_DM_SERVICE_TELEMETRY_CPU 143
// GENERAL_CALLBACK_DEPTH: exact u16 words, 0..65535 each; count; general callback depth. Width 2 (through field 148).
#define DOGMOS_DM_SERVICE_TELEMETRY_GENERAL_CALLBACK_DEPTH 147
// REACTION_CALLBACK_DEPTH: exact u16 words, 0..65535 each; count; reaction callback depth. Width 2 (through field 150).
#define DOGMOS_DM_SERVICE_TELEMETRY_REACTION_CALLBACK_DEPTH 149
// REACTION_TRANSACTION_DEPTH: exact u16 words, 0..65535 each; count; reaction transaction depth. Width 2 (through field 152).
#define DOGMOS_DM_SERVICE_TELEMETRY_REACTION_TRANSACTION_DEPTH 151
// REACTION_TRANSACTION_HIGH_WATER: exact u16 words, 0..65535 each; count; reaction transaction high water. Width 2 (through field 154).
#define DOGMOS_DM_SERVICE_TELEMETRY_REACTION_TRANSACTION_HIGH_WATER 153
// FRONTIER_COUNT: exact u16 words, 0..65535 each; count; frontier count. Width 2 (through field 156).
#define DOGMOS_DM_SERVICE_TELEMETRY_FRONTIER_COUNT 155
// STAGE_KIND: exact u16 words, 0..65535 each; count; stage kind. Width 2 (through field 158).
#define DOGMOS_DM_SERVICE_TELEMETRY_STAGE_KIND 157
// FRONTIER_UPLOAD_BYTES: exact u16 words, 0..65535 each; bytes; frontier upload bytes. Width 4 (through field 162).
#define DOGMOS_DM_SERVICE_TELEMETRY_FRONTIER_UPLOAD_BYTES 159
// STAGE_EPOCH: exact u16 words, 0..65535 each; identity; stage epoch. Width 4 (through field 166).
#define DOGMOS_DM_SERVICE_TELEMETRY_STAGE_EPOCH 163
// STAGE_CURSOR: exact u16 words, 0..65535 each; count; stage cursor. Width 2 (through field 168).
#define DOGMOS_DM_SERVICE_TELEMETRY_STAGE_CURSOR 167
// STAGE_REMAINING: exact u16 words, 0..65535 each; count; stage remaining. Width 2 (through field 170).
#define DOGMOS_DM_SERVICE_TELEMETRY_STAGE_REMAINING 169
// TOPOLOGY_REVISION: exact u16 words, 0..65535 each; identity; topology revision. Width 4 (through field 174).
#define DOGMOS_DM_SERVICE_TELEMETRY_TOPOLOGY_REVISION 171
// REUSABLE_WORKSET_BYTES: exact u16 words, 0..65535 each; bytes; reusable workset bytes. Width 4 (through field 178).
#define DOGMOS_DM_SERVICE_TELEMETRY_REUSABLE_WORKSET_BYTES 175
// PACKED_TOPOLOGY_BYTES: exact u16 words, 0..65535 each; bytes; packed topology bytes. Width 4 (through field 182).
#define DOGMOS_DM_SERVICE_TELEMETRY_PACKED_TOPOLOGY_BYTES 179
// JOB: exact u16 words, 0..65535 each; identity; job. Width 4 (through field 186).
#define DOGMOS_DM_SERVICE_TELEMETRY_JOB 183
// JOB_STATUS: exact u16 words, 0..65535 each; status; job status. Width 2 (through field 188).
#define DOGMOS_DM_SERVICE_TELEMETRY_JOB_STATUS 187
// JOB_AGE: exact u16 words, 0..65535 each; nanoseconds; job age. Width 4 (through field 192).
#define DOGMOS_DM_SERVICE_TELEMETRY_JOB_AGE 189
// PREPARE_CALLS: exact u16 words, 0..65535 each; count; prepare calls. Width 4 (through field 196).
#define DOGMOS_DM_SERVICE_TELEMETRY_PREPARE_CALLS 193
// PREPARE_TOTAL_NS: exact u16 words, 0..65535 each; nanoseconds; prepare total ns. Width 4 (through field 200).
#define DOGMOS_DM_SERVICE_TELEMETRY_PREPARE_TOTAL_NS 197
// PREPARE_MAX_NS: exact u16 words, 0..65535 each; nanoseconds; prepare max ns. Width 4 (through field 204).
#define DOGMOS_DM_SERVICE_TELEMETRY_PREPARE_MAX_NS 201
// PREPARE_LAST_NS: exact u16 words, 0..65535 each; nanoseconds; prepare last ns. Width 4 (through field 208).
#define DOGMOS_DM_SERVICE_TELEMETRY_PREPARE_LAST_NS 205
// COMMIT_CALLS: exact u16 words, 0..65535 each; count; commit calls. Width 4 (through field 212).
#define DOGMOS_DM_SERVICE_TELEMETRY_COMMIT_CALLS 209
// COMMIT_TOTAL_NS: exact u16 words, 0..65535 each; nanoseconds; commit total ns. Width 4 (through field 216).
#define DOGMOS_DM_SERVICE_TELEMETRY_COMMIT_TOTAL_NS 213
// COMMIT_MAX_NS: exact u16 words, 0..65535 each; nanoseconds; commit max ns. Width 4 (through field 220).
#define DOGMOS_DM_SERVICE_TELEMETRY_COMMIT_MAX_NS 217
// COMMIT_LAST_NS: exact u16 words, 0..65535 each; nanoseconds; commit last ns. Width 4 (through field 224).
#define DOGMOS_DM_SERVICE_TELEMETRY_COMMIT_LAST_NS 221
// PUBLICATION_RETRIES: exact u16 words, 0..65535 each; count; publication retries. Width 4 (through field 228).
#define DOGMOS_DM_SERVICE_TELEMETRY_PUBLICATION_RETRIES 225
// COMPLETED_JOBS: exact u16 words, 0..65535 each; count; completed jobs. Width 4 (through field 232).
#define DOGMOS_DM_SERVICE_TELEMETRY_COMPLETED_JOBS 229
// CANCELLED_JOBS: exact u16 words, 0..65535 each; count; cancelled jobs. Width 4 (through field 236).
#define DOGMOS_DM_SERVICE_TELEMETRY_CANCELLED_JOBS 233

// Existing DM names retained exactly. Callback event aliases are zero-relative offsets.
#define DOGMOS_SERVICE_TELEMETRY_WORDS 236
#define DOGMOS_JOB_TELEMETRY_START 183
#define DOGMOS_JOB_TELEMETRY_STATUS 187
#define DOGMOS_JOB_TELEMETRY_COUNTERS 189
#define DOGMOS_JOB_RESPONSE_FIELDS 26
#define DOGMOS_JOB_STATUS 5
#define DOGMOS_JOB_STAGE 6
#define DOGMOS_CALLBACK_HEADER_FIELDS 12
#define DOGMOS_CALLBACK_EVENT_FIELDS 36
#define DOGMOS_CALLBACK_EVENT_START 13
#define DOGMOS_CALLBACK_TRANSACTION_WORD 4
#define DOGMOS_CALLBACK_SCOPE_FIELD 8
#define DOGMOS_CALLBACK_KIND_FIELD 9
#define DOGMOS_CALLBACK_SUBJECT_SLOT_FIELD 11
#define DOGMOS_CALLBACK_SUBJECT_GENERATION_FIELD 13
#define DOGMOS_CALLBACK_TARGET_SLOT_FIELD 15
#define DOGMOS_CALLBACK_TARGET_GENERATION_FIELD 17
#define DOGMOS_CALLBACK_VALUES_FIELD 19
#define DOGMOS_CALLBACK_AUX_FIELD 23
#define DOGMOS_CALLBACK_CONTINUATION_TOKEN_FIELD 26
#define DOGMOS_TURF_LIFECYCLE_FIELDS 6
#define DOGMOS_TURF_ADJACENCY_FIELDS 6
#define DOGMOS_TURF_HEAT_FIELDS 7
#define DOGMOS_TURF_HEAT_ADJACENCY_FIELDS 5
#define DOGMOS_MIXTURE_SNAPSHOT_FIELDS 42
#define DOGMOS_MIXTURE_SNAPSHOT_REVISION_LOW 1
#define DOGMOS_MIXTURE_SNAPSHOT_REVISION_HIGH 2
#define DOGMOS_MIXTURE_SNAPSHOT_GAS_COUNT 3
#define DOGMOS_MIXTURE_SNAPSHOT_TEMPERATURE 4
#define DOGMOS_MIXTURE_SNAPSHOT_VOLUME 5
#define DOGMOS_MIXTURE_SNAPSHOT_TOTAL_MOLES 7
#define DOGMOS_MIXTURE_SNAPSHOT_PRESSURE 8
#define DOGMOS_MIXTURE_SNAPSHOT_HEAT_CAPACITY 9
#define DOGMOS_MIXTURE_SNAPSHOT_IMMUTABLE 10
#define DOGMOS_MIXTURE_SNAPSHOT_GASES_START 11
#define DOGMOS_PIPENET_RECONCILE_RECORD_FIELDS 44
#define DOGMOS_STAGE_RESPONSE_FIELDS 13
#define DOGMOS_STAGE_RESPONSE_PENDING 5
