//THIS FILE IS AUTOMATICALLY GENERATED BY DOGMOS, PLEASE DO NOT TOUCH IT
//PROC DEFINITIONS MAY MOVE AROUND, THIS IS NORMAL

#define DOGMOS (world.system_type == UNIX ? "libdogmos" : "dogmos")

/proc/dogmos_abi_version()
	return call_ext(DOGMOS, "byond:dogmos_abi_version_ffi")()

/proc/dogmos_callback_drain(fields)
	return call_ext(DOGMOS, "byond:dogmos_callback_drain_ffi")(fields)

/proc/dogmos_continuation_adjust_multiple(fields)
	return call_ext(DOGMOS, "byond:dogmos_continuation_adjust_multiple_ffi")(fields)

/proc/dogmos_continuation_cancel(fields)
	return call_ext(DOGMOS, "byond:dogmos_continuation_cancel_ffi")(fields)

/proc/dogmos_continuation_command(fields)
	return call_ext(DOGMOS, "byond:dogmos_continuation_command_ffi")(fields)

/proc/dogmos_continuation_resume(fields)
	return call_ext(DOGMOS, "byond:dogmos_continuation_resume_ffi")(fields)

/proc/dogmos_feature_fingerprint()
	return call_ext(DOGMOS, "byond:dogmos_feature_fingerprint_ffi")()

/proc/dogmos_frontier_add(records)
	return call_ext(DOGMOS, "byond:dogmos_frontier_add_ffi")(records)

/proc/dogmos_frontier_append(records)
	return call_ext(DOGMOS, "byond:dogmos_frontier_append_ffi")(records)

/proc/dogmos_frontier_begin(fields)
	return call_ext(DOGMOS, "byond:dogmos_frontier_begin_ffi")(fields)

/proc/dogmos_frontier_commit(fields)
	return call_ext(DOGMOS, "byond:dogmos_frontier_commit_ffi")(fields)

/proc/dogmos_frontier_remove(records)
	return call_ext(DOGMOS, "byond:dogmos_frontier_remove_ffi")(records)

/proc/dogmos_gas_metadata_install(numeric_records, keys, names, product_records)
	return call_ext(DOGMOS, "byond:dogmos_gas_metadata_install_ffi")(numeric_records, keys, names, product_records)

/proc/dogmos_mixture_adjust_multiple(fields)
	return call_ext(DOGMOS, "byond:dogmos_mixture_adjust_multiple_ffi")(fields)

/proc/dogmos_mixture_command(fields)
	return call_ext(DOGMOS, "byond:dogmos_mixture_command_ffi")(fields)

/proc/dogmos_mixture_lifecycle_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_mixture_lifecycle_batch_ffi")(entries)

/proc/dogmos_mixture_snapshot(fields)
	return call_ext(DOGMOS, "byond:dogmos_mixture_snapshot_ffi")(fields)

/proc/dogmos_mixture_snapshot_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_mixture_snapshot_batch_ffi")(entries)

/proc/dogmos_mixture_state_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_mixture_state_batch_ffi")(entries)

/proc/dogmos_pipenet_reconcile(entries)
	return call_ext(DOGMOS, "byond:dogmos_pipenet_reconcile_ffi")(entries)

/proc/dogmos_process_metrics()
	return call_ext(DOGMOS, "byond:dogmos_process_metrics_ffi")()

/proc/dogmos_protocol_version()
	return call_ext(DOGMOS, "byond:dogmos_protocol_version_ffi")()

/proc/dogmos_reaction_metadata_install(numeric_records, keys, requirement_records)
	return call_ext(DOGMOS, "byond:dogmos_reaction_metadata_install_ffi")(numeric_records, keys, requirement_records)

/proc/dogmos_service_health()
	return call_ext(DOGMOS, "byond:dogmos_service_health_ffi")()

/proc/dogmos_service_pid()
	return call_ext(DOGMOS, "byond:dogmos_service_pid_ffi")()

/proc/dogmos_service_shutdown()
	return call_ext(DOGMOS, "byond:dogmos_service_shutdown_ffi")()

/proc/dogmos_service_start(service_path)
	return call_ext(DOGMOS, "byond:dogmos_service_start_ffi")(service_path)

/proc/dogmos_service_telemetry()
	return call_ext(DOGMOS, "byond:dogmos_service_telemetry_ffi")()

/proc/dogmos_service_world_generation()
	return call_ext(DOGMOS, "byond:dogmos_service_world_generation_ffi")()

/proc/dogmos_simulation_stage(fields)
	return call_ext(DOGMOS, "byond:dogmos_simulation_stage_ffi")(fields)

/proc/dogmos_source_revision()
	return call_ext(DOGMOS, "byond:dogmos_source_revision_ffi")()

/proc/dogmos_stage_job_cancel(fields)
	return call_ext(DOGMOS, "byond:dogmos_stage_job_cancel_ffi")(fields)

/proc/dogmos_stage_job_commit(fields)
	return call_ext(DOGMOS, "byond:dogmos_stage_job_commit_ffi")(fields)

/proc/dogmos_stage_job_poll(fields)
	return call_ext(DOGMOS, "byond:dogmos_stage_job_poll_ffi")(fields)

/proc/dogmos_stage_job_submit(fields)
	return call_ext(DOGMOS, "byond:dogmos_stage_job_submit_ffi")(fields)

/proc/dogmos_turf_adjacency_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_turf_adjacency_batch_ffi")(entries)

/proc/dogmos_turf_heat_adjacency_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_turf_heat_adjacency_batch_ffi")(entries)

/proc/dogmos_turf_heat_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_turf_heat_batch_ffi")(entries)

/proc/dogmos_turf_heat_snapshot(fields)
	return call_ext(DOGMOS, "byond:dogmos_turf_heat_snapshot_ffi")(fields)

/proc/dogmos_turf_lifecycle_batch(entries)
	return call_ext(DOGMOS, "byond:dogmos_turf_lifecycle_batch_ffi")(entries)

/*
 * Generated process-metrics DM adapter reference.
 * Authority: dogmos-byond/src/process_metrics_layout.rs; regenerate with generate_bindings.
 * /proc/dogmos_process_metrics returns 28 exact u16 words in an f32 list.
 * Scalar words are low-first; positions below are one-based DM list indices.
 * Unknown availability bits are rejected; an unavailable counter must be zero.
 * Words 1-2 (u32): DOGMOS_PROCESS_LAYOUT_WORD - Adapter layout version (must match DOGMOS_PROCESS_METRICS_LAYOUT_VERSION).
 * Words 3-4 (u32): DOGMOS_PROCESS_HOST_FLAGS_WORD - DreamDaemon availability flags; host CPU is not included in this adapter.
 * Words 5-6 (u32): DOGMOS_PROCESS_SERVICE_FLAGS_WORD - dogmosd availability flags, independent of DreamDaemon flags.
 * Words 7-8 (u32): DOGMOS_PROCESS_RESERVED_WORD - Reserved; must be zero.
 * Words 9-12 (u64): DOGMOS_PROCESS_HOST_PRIVATE_BYTES_WORD - DreamDaemon private/committed bytes (platform sampler semantics).
 * Words 13-16 (u64): DOGMOS_PROCESS_HOST_VIRTUAL_BYTES_WORD - DreamDaemon virtual address-space bytes.
 * Words 17-20 (u64): DOGMOS_PROCESS_HOST_WORKING_SET_BYTES_WORD - DreamDaemon working-set/resident bytes.
 * Words 21-24 (u64): DOGMOS_PROCESS_SERVICE_RSS_BYTES_WORD - dogmosd resident bytes; never added to DreamDaemon memory.
 * Words 25-28 (u64): DOGMOS_PROCESS_SERVICE_CPU_MILLISECONDS_WORD - dogmosd cumulative CPU milliseconds (not elapsed wall time).
 */
#define DOGMOS_PROCESS_METRICS_WORDS 28
#define DOGMOS_PROCESS_METRICS_LAYOUT_VERSION 1
#define DOGMOS_PROCESS_WORD_BASE 65536
#define DOGMOS_PROCESS_WORD_MAX 65535
#define DOGMOS_PROCESS_LAYOUT_WORD 1
#define DOGMOS_PROCESS_HOST_FLAGS_WORD 3
#define DOGMOS_PROCESS_SERVICE_FLAGS_WORD 5
#define DOGMOS_PROCESS_RESERVED_WORD 7
#define DOGMOS_PROCESS_HOST_PRIVATE_BYTES_WORD 9
#define DOGMOS_PROCESS_HOST_VIRTUAL_BYTES_WORD 13
#define DOGMOS_PROCESS_HOST_WORKING_SET_BYTES_WORD 17
#define DOGMOS_PROCESS_SERVICE_RSS_BYTES_WORD 21
#define DOGMOS_PROCESS_SERVICE_CPU_MILLISECONDS_WORD 25
#define DOGMOS_DREAMDAEMON_PRIVATE_BYTES_AVAILABLE 1
#define DOGMOS_DREAMDAEMON_VIRTUAL_BYTES_AVAILABLE 2
#define DOGMOS_DREAMDAEMON_WORKING_SET_BYTES_AVAILABLE 4
#define DOGMOS_DREAMDAEMON_ALL_AVAILABLE 7
#define DOGMOS_SERVICE_RSS_BYTES_AVAILABLE 1
#define DOGMOS_SERVICE_CPU_MILLISECONDS_AVAILABLE 2
#define DOGMOS_SERVICE_ALL_AVAILABLE 3
